homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('privacy/', views.privacy, name='privacy'),
    path('register/', views.register, name='register'),
    path('', views.index, name='index')
]

mainichi/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('messaging/', include('messaging.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('homepage.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

messaging/urls.py
from django.urls import path, re_path
from .views import index, UsersList, MessagesList, NewMessage

app_name = 'messaging'

urlpatterns = [
    path('api/users/', UsersList.as_view(), name='users_api'),
    path('api/user_messages/', MessagesList.as_view(), name='messages_list_api'),
    path('api/new_message/<int:sender_id>/<int:receiver_id>/(?P<message_text>[-\w]+)/', NewMessage.as_view(), name='new_message_api'),
    path('', index, name='index'),
]

homepage/models.py
from django.db import models

# Create your models here.

messaging/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Message(models.Model):
    conversation_id = models.CharField(max_length=100)
    datetime = models.DateTimeField(auto_now=False)
    sender_id = models.IntegerField(default=-1)
    receiver_id = models.IntegerField(default=-1)
    sender_user = models.ForeignKey(User, on_delete=models.CASCADE, blank = True,null=True, related_name = 'sender_user')
    receiver_user = models.ForeignKey(User, on_delete=models.CASCADE, blank = True,null=True, related_name = 'receiver_user')
    text = models.CharField(max_length=500)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.conversation_id

homepage/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    context = {}
    return render(request, 'homepage/homepage.html', context)

def register(request):
    context = {}
    return render(request, 'homepage/register.html', context)

def privacy(request):
    context = {}
    return render(request, 'homepage/homepage.html', context)

messaging/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from datetime import datetime
from django.contrib.auth.models import User
from .models import Message
from .serializers import UserSerializer
from .serializers import MessageSerializer



@login_required(login_url='/')
def index(request):
    return render(request, 'messaging/messaging.html')

class UsersList(generics.ListAPIView):
    serializer_class = UserSerializer
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        user_id = self.request.user.id
        queryset = User.objects.all().exclude(id=user_id)
        return queryset

class MessagesList(generics.ListAPIView):
    serializer_class = MessageSerializer
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        user_id = self.request.user.id
        queryset = Message.objects.all()
        queryset = queryset.filter(sender_id = user_id) | queryset.filter(receiver_id = user_id)
        queryset = queryset.order_by('datetime', 'id')
        return queryset

class NewMessage(generics.ListAPIView):
    serializer_class = MessageSerializer
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        user_id = self.request.user.id
        sender_id = self.kwargs.get('sender_id', "")
        receiver_id = self.kwargs.get('receiver_id', "")
        message_text = self.kwargs.get('message_text', "")
        dt = datetime.now()
        d_truncated = datetime(dt.year, dt.month, dt.day, dt.hour, dt.minute)

        if str(user_id) != str(sender_id):
            return Message.objects.none()

        if sender_id<receiver_id:
            conversation_id = str(receiver_id)+'_'+str(sender_id)
        else:
            conversation_id = str(sender_id)+'_'+str(receiver_id)

        if conversation_id == "0_0":
            return Message.objects.none()

        sender = User.objects.get(id=sender_id)
        receiver = User.objects.get(id=receiver_id)

        new_message, created = Message.objects.get_or_create(conversation_id=conversation_id, datetime=d_truncated, sender_id=sender_id, receiver_id=receiver_id, sender_user=sender, receiver_user=receiver, text=message_text)
        new_message.save()
        
        return Message.objects.none()

homepage/templates/base.html
{% load cache static i18n %}


<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/png" href="{% static 'assets/img/favicon.ico' %}">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		
		<title>Mainichi Chat</title>

		<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
		<meta name="viewport" content="width=device-width" />
		
		<link href="{% static 'assets/css/bootstrap.css' %}" rel="stylesheet" />
		<link href="{% static 'assets/css/ct-paper.css' %}" rel="stylesheet"/>
		<link href="{% static 'assets/css/demo.css' %}" rel="stylesheet" /> 
		<link href="{% static 'assets/css/examples.css' %}" rel="stylesheet" /> 
			
		<!--     Fonts and icons     -->
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
		<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
		  
	</head>
	<body class="full-screen register">

		<nav class="navbar navbar-ct-transparent navbar-fixed-top" role="navigation-demo" id="register-navbar" style="position: absolute;">
			<div class="container">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">Mainichi Chat</a>
				</div>
			
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="navigation-example-2">
				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
					<li>
						<a href="{% url 'homepage:index' %}" class="btn btn-simple">Logout</a>
					</li>
					<li>
						<a href="{% url 'messaging:index' %}" class="btn btn-simple">Messaging</a>
					</li>
					{% else %}
					<li>
						<a href="{% url 'homepage:index' %}" class="btn btn-simple">Login</a>
					</li>
					{% endif %}
				</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-->
		</nav> 
		
		<div class="wrapper">
			<div class="background" style="background-image: url({% static 'assets/img/landscape.jpg' %});"> 
				<div class="filter-black"></div>
				
				
                {% block content %}{% endblock %}

				<div class="demo-footer text-center">
						<h6>&copy; 2020, made with <i class="fa fa-heart heart"></i> by <a href="https://hexql.com" target="_blank">Mario Dobaj</a></h6>
				</div>
			</div>
		</div>      

	</body> 


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js" type="text/javascript"></script>
    <script src="{% static 'assets/js/jquery-ui-1.10.4.custom.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/bootstrap.js' %}" type="text/javascript"></script>
    <!--  Plugins -->
    <script src="{% static 'assets/js/ct-paper.js' %}"></script>

	{% block extra_js %}{% endblock %}

</html>

homepage/templates/homepage/homepage.html
{% extends "base.html" %}

{% block content %}
    
    <div class="container" style="margin-top: 7%;>
        <div class="row">
            <div class="col-md-3 col-sm-2 col-xs-12"></div>
            <div class="col-md-6 col-sm-8 col-xs-12">
                
                {% if user.is_authenticated %}
                <div class="demo-card" style="margin: auto; margin-top: 30px; min-height: auto;">
                    <h3 class="title text-center">You are logged in</h3>
                    <h5 class="text-center">Go to:</h5>
                    <div class="social" style="margin-top: 0px;">
                        <a href="/messaging/" class="btn btn-fill btn-icon" style="margin-top: 0px;">
                            Messaging
                        </a>
                    </div>

                    <div class="division">
                        <div class="line l"></div>
                        <span>or</span>
                        <div class="line r"></div>
                    </div>
                    <form class="loginForm" method="POST" action="{% url 'account_logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-fill btn-block">Logout</button>
                    </form>
                </div>

                {% else %}

                <div class="demo-card" style="margin: auto; margin-top: 30px;">
                    <h3 class="title text-center">Login</h3>
                    <div class="social">
                        <a href="accounts/facebook/login/{% if '/?next=/messaging/' in request.get_full_path %}?next=/messaging/{% endif %}" class="btn btn-fill btn-icon btn-facebook">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </div>

                    <div class="division">
                        <div class="line l"></div>
                        <span>or</span>
                        <div class="line r"></div>
                    </div>
                    <form class="loginForm" method="POST" action="/accounts/login/{% if '/?next=/messaging/' in request.get_full_path %}?next=/messaging/{% endif %}">
                        {% csrf_token %}
                        <input type="text" name="login" class="form-control" required id="id_login" placeholder="Username">

                        <input type="password" name="password" class="form-control" required required id="id_password" placeholder="Password">
                                              
                        <button type="submit" class="btn btn-fill btn-block">Login</button>
                    </form>
                    <br>
                    <a href="/register/" class="btn btn-fill btn-block">Register</a>
                </div>
                {% endif %}

            </div>
            <div class="col-md-3 col-sm-2 col-xs-12"></div>
        </div>
    </div> 

{% endblock content %}

homepage/templates/homepage/register.html
{% extends "base.html" %}

{% block content %}

    <div class="container" style="margin-top: 7%;>
        <div class="row">
            <div class="col-md-3 col-sm-2 col-xs-12"></div>
            <div class="col-md-6 col-sm-8 col-xs-12">
                
                {% if user.is_authenticated %}
                <div class="demo-card" style="margin: auto; margin-top: 30px; min-height: auto;">
                    <h3 class="title text-center">You are logged in</h3>
                    <h5 class="text-center">Go to:</h5>
                    <div class="social" style="margin-top: 0px;">
                        <a href="/messaging/" class="btn btn-fill btn-icon" style="margin-top: 0px;">
                            Messaging
                        </a>
                    </div>

                    <div class="division">
                        <div class="line l"></div>
                        <span>or</span>
                        <div class="line r"></div>
                    </div>
                    <form class="loginForm" method="POST" action="{% url 'account_logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-fill btn-block">Logout</button>
                    </form>
                </div>

                {% else %}

                <div class="demo-card" style="margin: auto; margin-top: 30px;">
                    <h3 class="title text-center">Register</h3>
                    <form class="loginForm" method="POST" action="/accounts/signup/{% if '/?next=/messaging/' in request.get_full_path %}?next=/messaging/{% endif %}">
                        {% csrf_token %}
                        <input type="text" name="username" class="form-control" required id="id_username" placeholder="Username">

                        <input type="password" name="password1" class="form-control" required required id="id_password1" minlength="8" placeholder="Password">
                        <input type="password" name="password2" class="form-control" required required id="id_password2" minlength="8" placeholder="Password (Again)">
                                              
                        <button type="submit" class="btn btn-fill btn-block">Register</button>
                    </form>
                    <br>
                    <a href="/" class="btn btn-fill btn-block">Login</a>
                </div>
                {% endif %}

            </div>
            <div class="col-md-3 col-sm-2 col-xs-12"></div>
        </div>
    </div> 

{% endblock content %}